version: "3.8"

services:
  api:
    build: .
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/email_service
      - RABBITMQ_URL=amqp://rabbitmq
      - NODE_ENV=production
      - PORT=3001
    depends_on:
      - postgres
      - rabbitmq
    restart: unless-stopped

  email-processor:
    build: .
    command: node dist/processor/processor.main.js
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/email_service
      - RABBITMQ_URL=amqp://rabbitmq
      - NODE_ENV=production
    depends_on:
      - postgres
      - rabbitmq
    restart: unless-stopped
    # Can be scaled: docker-compose up -d --scale email-processor=3

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=email_service
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
  rabbitmq-data:
